name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
      - uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: yarn install & build
        run: |
          yarn
          yarn build

      - name: lighthouse mobile audit
        run: yarn lhci:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: lighthouse desktop audit
        run: yarn lhci:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
