name: CI
# on:
#   schedule:
#     - cron: '0 10 * * 3,6'
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse on NBC.com and upload data to private lhci server
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: 'https://www.nbc.com/'
          configPath: './lighthouserc.json'
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}
